// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bvnu
double bvnu(double dh, double dk, double r);
RcppExport SEXP _sov_bvnu(SEXP dhSEXP, SEXP dkSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type dh(dhSEXP);
    Rcpp::traits::input_parameter< double >::type dk(dkSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(bvnu(dh, dk, r));
    return rcpp_result_gen;
END_RCPP
}
// mvnxpb
double mvnxpb(arma::mat r, arma::vec a, arma::vec b);
RcppExport SEXP _sov_mvnxpb(SEXP rSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnxpb(r, a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sov_bvnu", (DL_FUNC) &_sov_bvnu, 3},
    {"_sov_mvnxpb", (DL_FUNC) &_sov_mvnxpb, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sov(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
