# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' compute P(x > dh, y > dk) for x,y ~ bivariate normal with correlation r
bvnu <- function(dh, dk, r) {
    .Call(`_sov_bvnu`, dh, dk, r)
}

mvnxpb <- function(r, a, b) {
    .Call(`_sov_mvnxpb`, r, a, b)
}

